/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TheCellar {
  export type Slot0Struct = {
    locked: BigNumberish;
    epochId: BigNumberish;
    initPrice: BigNumberish;
    startTime: BigNumberish;
  };

  export type Slot0StructOutput = [
    locked: bigint,
    epochId: bigint,
    initPrice: bigint,
    startTime: bigint
  ] & { locked: bigint; epochId: bigint; initPrice: bigint; startTime: bigint };
}

export interface TheCellarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ABS_MAX_INIT_PRICE"
      | "ABS_MIN_INIT_PRICE"
      | "MAX_EPOCH_PERIOD"
      | "MAX_PRICE_MULTIPLIER"
      | "MIN_EPOCH_PERIOD"
      | "MIN_PRICE_MULTIPLIER"
      | "PRICE_MULTIPLIER_SCALE"
      | "buy"
      | "epochPeriod"
      | "getPrice"
      | "getSlot0"
      | "minInitPrice"
      | "owner"
      | "paymentReceiver"
      | "paymentToken"
      | "priceMultiplier"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Cellar__Buy" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ABS_MAX_INIT_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ABS_MIN_INIT_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EPOCH_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PRICE_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EPOCH_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PRICE_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_MULTIPLIER_SCALE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "getSlot0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minInitPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ABS_MAX_INIT_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ABS_MIN_INIT_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EPOCH_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PRICE_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EPOCH_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PRICE_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_MULTIPLIER_SCALE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSlot0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minInitPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace Cellar__BuyEvent {
  export type InputTuple = [
    buyer: AddressLike,
    assetsReceiver: AddressLike,
    paymentAmount: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    assetsReceiver: string,
    paymentAmount: bigint
  ];
  export interface OutputObject {
    buyer: string;
    assetsReceiver: string;
    paymentAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TheCellar extends BaseContract {
  connect(runner?: ContractRunner | null): TheCellar;
  waitForDeployment(): Promise<this>;

  interface: TheCellarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ABS_MAX_INIT_PRICE: TypedContractMethod<[], [bigint], "view">;

  ABS_MIN_INIT_PRICE: TypedContractMethod<[], [bigint], "view">;

  MAX_EPOCH_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  MIN_EPOCH_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  PRICE_MULTIPLIER_SCALE: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [
      assetsReceiver: AddressLike,
      epochId: BigNumberish,
      deadline: BigNumberish,
      maxPaymentTokenAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  epochPeriod: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getSlot0: TypedContractMethod<[], [TheCellar.Slot0StructOutput], "view">;

  minInitPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentReceiver: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  priceMultiplier: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ABS_MAX_INIT_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ABS_MIN_INIT_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EPOCH_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EPOCH_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_MULTIPLIER_SCALE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      assetsReceiver: AddressLike,
      epochId: BigNumberish,
      deadline: BigNumberish,
      maxPaymentTokenAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSlot0"
  ): TypedContractMethod<[], [TheCellar.Slot0StructOutput], "view">;
  getFunction(
    nameOrSignature: "minInitPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Cellar__Buy"
  ): TypedContractEvent<
    Cellar__BuyEvent.InputTuple,
    Cellar__BuyEvent.OutputTuple,
    Cellar__BuyEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "Cellar__Buy(address,address,uint256)": TypedContractEvent<
      Cellar__BuyEvent.InputTuple,
      Cellar__BuyEvent.OutputTuple,
      Cellar__BuyEvent.OutputObject
    >;
    Cellar__Buy: TypedContractEvent<
      Cellar__BuyEvent.InputTuple,
      Cellar__BuyEvent.OutputTuple,
      Cellar__BuyEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
