/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iPseudoswapSol from "./IPseudoswap.sol";
export type { iPseudoswapSol };
export type { IERC6551Account } from "./IERC6551Account";
export type { IERC6551Registry } from "./IERC6551Registry";
export type { IUniswapV3Router } from "./IUniswapV3Router";
