/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPseudoswapFactory,
  IPseudoswapFactoryInterface,
} from "../../../../contracts/interfaces/IPseudoswap.sol/IPseudoswapFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "createPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPseudoswapFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPseudoswapFactoryInterface {
    return new Interface(_abi) as IPseudoswapFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPseudoswapFactory {
    return new Contract(address, _abi, runner) as unknown as IPseudoswapFactory;
  }
}
