import { WorldContentEntry } from './content/types/world-content';
import { Geography } from './generation/types/world-generation';

export const DEMO_MAPS: Geography[] = [
    {
        id: 'demo-map-woods',
        name: 'The Whispering Woods',
        description: 'A dense, ancient forest where the wind speaks in riddles. Sunlight barely penetrates the canopy, and strange glowing flora lights the path.',
        type: 'geography',
        geographyType: 'forest',
        location: { x: 0, y: 0 },
        features: ['Ancient Trees', 'Glowing Mushrooms', 'Fog'],
        climate: 'temperate',
        resources: ['wood', 'herbs'],
        dangers: ['wolves', 'spirits'],
        connections: ['demo-map-ruins'],
        createdBy: 'primordial-nature',
        magnitude: 'medium',
        createdAt: new Date(),
        discoveredAt: new Date(),
        parentId: null,
        metadata: {},
    },
    {
        id: 'demo-map-ruins',
        name: 'The Sunken Ruins',
        description: 'The remains of a once-great civilization, now half-submerged in a swamp. Stone structures jut out of the murky water, covered in moss and vines.',
        type: 'geography',
        geographyType: 'island', // Using island as proxy for swamp/ruins for now
        location: { x: 10, y: 0 },
        features: ['Crumbling Stone', 'Murky Water', 'Vines'],
        climate: 'humid',
        resources: ['stone', 'artifacts'],
        dangers: ['slimes', 'undead'],
        connections: ['demo-map-woods', 'demo-map-peak'],
        createdBy: 'primordial-water',
        magnitude: 'medium',
        createdAt: new Date(),
        discoveredAt: new Date(),
        parentId: null,
        metadata: {},
    },
    {
        id: 'demo-map-peak',
        name: "The Dragon's Peak",
        description: 'A jagged mountain peak that pierces the clouds. The air is thin and smells of sulfur. It is said a great beast once roosted here.',
        type: 'geography',
        geographyType: 'mountain_range',
        location: { x: 20, y: 0 },
        features: ['Jagged Rocks', 'Lava Flows', 'Ash'],
        climate: 'arid',
        resources: ['ore', 'obsidian'],
        dangers: ['drakes', 'elementals'],
        connections: ['demo-map-ruins'],
        createdBy: 'primordial-fire',
        magnitude: 'large',
        createdAt: new Date(),
        discoveredAt: new Date(),
        parentId: null,
        metadata: {},
    },
];

export const DEMO_ITEMS: WorldContentEntry[] = [
    // Woods Items
    {
        content: {
            id: 'item-woods-1',
            type: 'resource',
            name: 'Elder Wood Branch',
            description: 'A sturdy branch from an ancient tree, humming with faint magic.',
            parentId: 'demo-map-woods',
            createdAt: new Date(),
            discoveredAt: new Date(),
            metadata: {},
        },
        provenance: {
            contentId: 'item-woods-1',
            originId: 'demo-map-woods',
            creatorId: null,
            creationMethod: 'discovered',
            creationTime: new Date(),
            history: [],
            age: 100,
            materials: ['wood'],
            location: 'The Whispering Woods',
        },
        lore: {
            contentId: 'item-woods-1',
            story: 'Fallen from the great Elder Tree during the last storm.',
            significance: 'Crafting material for magical staves.',
            connections: [],
            enrichedAt: new Date(),
            version: 1,
        },
    },
    {
        content: {
            id: 'item-woods-2',
            type: 'item',
            name: 'Whispering Nut',
            description: 'A nut that seems to murmur when held close to the ear.',
            parentId: 'demo-map-woods',
            createdAt: new Date(),
            discoveredAt: new Date(),
            metadata: {},
        },
        provenance: {
            contentId: 'item-woods-2',
            originId: 'demo-map-woods',
            creatorId: null,
            creationMethod: 'discovered',
            creationTime: new Date(),
            history: [],
            age: 1,
            materials: ['organic'],
            location: 'The Whispering Woods',
        },
        lore: {
            contentId: 'item-woods-2',
            story: 'Found beneath a glowing mushroom patch.',
            significance: 'Can be used in alchemy to create silence potions.',
            connections: [],
            enrichedAt: new Date(),
            version: 1,
        },
    },
    // Ruins Items
    {
        content: {
            id: 'item-ruins-1',
            type: 'item',
            name: 'Rusted Coin',
            description: 'An old coin with indecipherable markings.',
            parentId: 'demo-map-ruins',
            createdAt: new Date(),
            discoveredAt: new Date(),
            metadata: {},
        },
        provenance: {
            contentId: 'item-ruins-1',
            originId: 'demo-map-ruins',
            creatorId: 'ancient-civ',
            creationMethod: 'crafted',
            creationTime: new Date(),
            history: [],
            age: 1000,
            materials: ['copper'],
            location: 'The Sunken Ruins',
        },
        lore: {
            contentId: 'item-ruins-1',
            story: 'Minted during the golden age of the Sunken Kingdom.',
            significance: 'Historical artifact.',
            connections: [],
            enrichedAt: new Date(),
            version: 1,
        },
    },
    // Peak Items
    {
        content: {
            id: 'item-peak-1',
            type: 'resource',
            name: 'Dragon Scale Shard',
            description: 'A sharp, warm fragment of a dragon scale.',
            parentId: 'demo-map-peak',
            createdAt: new Date(),
            discoveredAt: new Date(),
            metadata: {},
        },
        provenance: {
            contentId: 'item-peak-1',
            originId: 'demo-map-peak',
            creatorId: 'dragon',
            creationMethod: 'born',
            creationTime: new Date(),
            history: [],
            age: 500,
            materials: ['scale'],
            location: "The Dragon's Peak",
        },
        lore: {
            contentId: 'item-peak-1',
            story: 'Shed by the great dragon Ignis centuries ago.',
            significance: 'Highly heat resistant.',
            connections: [],
            enrichedAt: new Date(),
            version: 1,
        },
    },
];
