/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TavernKeeper {
  export type Slot0Struct = {
    locked: BigNumberish;
    epochId: BigNumberish;
    initPrice: BigNumberish;
    startTime: BigNumberish;
    dps: BigNumberish;
    miner: AddressLike;
    uri: string;
  };

  export type Slot0StructOutput = [
    locked: bigint,
    epochId: bigint,
    initPrice: bigint,
    startTime: bigint,
    dps: bigint,
    miner: string,
    uri: string
  ] & {
    locked: bigint;
    epochId: bigint;
    initPrice: bigint;
    startTime: bigint;
    dps: bigint;
    miner: string;
    uri: string;
  };
}

export interface TavernKeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ABS_MAX_INIT_PRICE"
      | "DEFAULT_RATE"
      | "DIVISOR"
      | "EPOCH_PERIOD"
      | "FEE"
      | "HALVING_PERIOD"
      | "INITIAL_DPS"
      | "MIN_INIT_PRICE"
      | "NEW_PRICE_MULTIPLIER"
      | "PRECISION"
      | "PRICE_MULTIPLIER"
      | "TAIL_DPS"
<<<<<<< HEAD
      | "TIER1_MAX_ID"
      | "TIER2_MAX_ID"
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
      | "UPGRADE_INTERFACE_VERSION"
      | "approve"
      | "balanceOf"
      | "calculatePendingTokens"
      | "claimOfficeRewards"
      | "claimTokens"
      | "getApproved"
      | "getDps"
<<<<<<< HEAD
      | "getMintPrice"
      | "getPendingOfficeRewards"
      | "getPrice"
      | "getSlot0"
      | "getTokensOfOwner"
      | "initialize"
      | "initializeOfficeV2"
      | "initializeRPG"
=======
      | "getPrice"
      | "getSlot0"
      | "initialize"
      | "initializeOfficeV2"
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
      | "isApprovedForAll"
      | "keepToken"
      | "lastClaimTime"
      | "lastOfficeClaimTimestamp"
      | "mintTavernKeeper"
      | "mintingRate"
      | "name"
      | "nonces"
      | "owner"
      | "ownerOf"
      | "proxiableUUID"
      | "renounceOwnership"
      | "safeMint"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setKeepTokenContract"
<<<<<<< HEAD
      | "setSigner"
      | "setTierPrices"
      | "setTreasury"
      | "signer"
=======
      | "setTreasury"
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
      | "slot0"
      | "supportsInterface"
      | "symbol"
      | "takeOffice"
<<<<<<< HEAD
      | "tier1Price"
      | "tier2Price"
      | "tier3Price"
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "treasury"
      | "upgradeToAndCall"
      | "v2StartTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "Initialized"
      | "KeepTokenUpdated"
      | "MetadataUpdate"
      | "OfficeEarningsClaimed"
<<<<<<< HEAD
      | "OfficeRewardsClaimed"
      | "OfficeTaken"
      | "OwnershipTransferred"
      | "PreviousKingPaid"
      | "SignerUpdated"
      | "TavernKeeperMinted"
      | "TavernKeeperMintedWithSignature"
      | "TierPricesUpdated"
=======
      | "OfficeTaken"
      | "OwnershipTransferred"
      | "PreviousKingPaid"
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
      | "TokensClaimed"
      | "Transfer"
      | "TreasuryFee"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ABS_MAX_INIT_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DIVISOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "EPOCH_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "HALVING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_DPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INIT_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NEW_PRICE_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PRICE_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TAIL_DPS", values?: undefined): string;
<<<<<<< HEAD
  encodeFunctionData(
    functionFragment: "TIER1_MAX_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER2_MAX_ID",
    values?: undefined
  ): string;
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePendingTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOfficeRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getDps", values?: undefined): string;
<<<<<<< HEAD
  encodeFunctionData(
    functionFragment: "getMintPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingOfficeRewards",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "getSlot0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokensOfOwner",
    values: [AddressLike]
  ): string;
=======
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "getSlot0", values?: undefined): string;
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeOfficeV2",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
<<<<<<< HEAD
    functionFragment: "initializeRPG",
    values?: undefined
  ): string;
  encodeFunctionData(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "keepToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastClaimTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastOfficeClaimTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintTavernKeeper",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintingRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeMint",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeepTokenContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
<<<<<<< HEAD
    functionFragment: "setSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierPrices",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;
=======
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  encodeFunctionData(functionFragment: "slot0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "takeOffice",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
<<<<<<< HEAD
    functionFragment: "tier1Price",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tier2Price",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tier3Price",
    values?: undefined
  ): string;
  encodeFunctionData(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "v2StartTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ABS_MAX_INIT_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DIVISOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "EPOCH_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "HALVING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_DPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INIT_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NEW_PRICE_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TAIL_DPS", data: BytesLike): Result;
<<<<<<< HEAD
  decodeFunctionResult(
    functionFragment: "TIER1_MAX_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER2_MAX_ID",
    data: BytesLike
  ): Result;
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePendingTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOfficeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDps", data: BytesLike): Result;
<<<<<<< HEAD
  decodeFunctionResult(
    functionFragment: "getMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingOfficeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSlot0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokensOfOwner",
    data: BytesLike
  ): Result;
=======
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSlot0", data: BytesLike): Result;
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeOfficeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
<<<<<<< HEAD
    functionFragment: "initializeRPG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keepToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastClaimTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastOfficeClaimTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintTavernKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKeepTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTierPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slot0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slot0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "takeOffice", data: BytesLike): Result;
<<<<<<< HEAD
  decodeFunctionResult(functionFragment: "tier1Price", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tier2Price", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tier3Price", data: BytesLike): Result;
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "v2StartTime",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeepTokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficeEarningsClaimedEvent {
  export type InputTuple = [king: AddressLike, amount: BigNumberish];
  export type OutputTuple = [king: string, amount: bigint];
  export interface OutputObject {
    king: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

<<<<<<< HEAD
export namespace OfficeRewardsClaimedEvent {
  export type InputTuple = [king: AddressLike, amount: BigNumberish];
  export type OutputTuple = [king: string, amount: bigint];
  export interface OutputObject {
    king: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
export namespace OfficeTakenEvent {
  export type InputTuple = [
    newKing: AddressLike,
    newPrice: BigNumberish,
    paidAmount: BigNumberish,
    uri: string
  ];
  export type OutputTuple = [
    newKing: string,
    newPrice: bigint,
    paidAmount: bigint,
    uri: string
  ];
  export interface OutputObject {
    newKing: string;
    newPrice: bigint;
    paidAmount: bigint;
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PreviousKingPaidEvent {
  export type InputTuple = [prevKing: AddressLike, amount: BigNumberish];
  export type OutputTuple = [prevKing: string, amount: bigint];
  export interface OutputObject {
    prevKing: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

<<<<<<< HEAD
export namespace SignerUpdatedEvent {
  export type InputTuple = [newSigner: AddressLike];
  export type OutputTuple = [newSigner: string];
  export interface OutputObject {
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TavernKeeperMintedEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [to: string, tokenId: bigint, price: bigint];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TavernKeeperMintedWithSignatureEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    price: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    tokenId: bigint,
    price: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    price: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierPricesUpdatedEvent {
  export type InputTuple = [
    t1: BigNumberish,
    t2: BigNumberish,
    t3: BigNumberish
  ];
  export type OutputTuple = [t1: bigint, t2: bigint, t3: bigint];
  export interface OutputObject {
    t1: bigint;
    t2: bigint;
    t3: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
export namespace TokensClaimedEvent {
  export type InputTuple = [tokenId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [tokenId: bigint, amount: bigint];
  export interface OutputObject {
    tokenId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryFeeEvent {
  export type InputTuple = [treasury: AddressLike, amount: BigNumberish];
  export type OutputTuple = [treasury: string, amount: bigint];
  export interface OutputObject {
    treasury: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TavernKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): TavernKeeper;
  waitForDeployment(): Promise<this>;

  interface: TavernKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ABS_MAX_INIT_PRICE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_RATE: TypedContractMethod<[], [bigint], "view">;

  DIVISOR: TypedContractMethod<[], [bigint], "view">;

  EPOCH_PERIOD: TypedContractMethod<[], [bigint], "view">;

  FEE: TypedContractMethod<[], [bigint], "view">;

  HALVING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  INITIAL_DPS: TypedContractMethod<[], [bigint], "view">;

  MIN_INIT_PRICE: TypedContractMethod<[], [bigint], "view">;

  NEW_PRICE_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  PRICE_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  TAIL_DPS: TypedContractMethod<[], [bigint], "view">;

<<<<<<< HEAD
  TIER1_MAX_ID: TypedContractMethod<[], [bigint], "view">;

  TIER2_MAX_ID: TypedContractMethod<[], [bigint], "view">;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  calculatePendingTokens: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  claimOfficeRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimTokens: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getDps: TypedContractMethod<[], [bigint], "view">;

<<<<<<< HEAD
  getMintPrice: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getPendingOfficeRewards: TypedContractMethod<[], [bigint], "view">;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  getPrice: TypedContractMethod<[], [bigint], "view">;

  getSlot0: TypedContractMethod<[], [TavernKeeper.Slot0StructOutput], "view">;

<<<<<<< HEAD
  getTokensOfOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  initialize: TypedContractMethod<[], [void], "nonpayable">;

  initializeOfficeV2: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

<<<<<<< HEAD
  initializeRPG: TypedContractMethod<[], [void], "nonpayable">;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  keepToken: TypedContractMethod<[], [string], "view">;

  lastClaimTime: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  lastOfficeClaimTimestamp: TypedContractMethod<[], [bigint], "view">;

  mintTavernKeeper: TypedContractMethod<
    [
      uri: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [bigint],
    "payable"
  >;

  mintingRate: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  safeMint: TypedContractMethod<
    [to: AddressLike, uri: string],
    [bigint],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setKeepTokenContract: TypedContractMethod<
    [_keepToken: AddressLike],
    [void],
    "nonpayable"
  >;

<<<<<<< HEAD
  setSigner: TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;

  setTierPrices: TypedContractMethod<
    [_t1: BigNumberish, _t2: BigNumberish, _t3: BigNumberish],
    [void],
    "nonpayable"
  >;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  slot0: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, string, string] & {
        locked: bigint;
        epochId: bigint;
        initPrice: bigint;
        startTime: bigint;
        dps: bigint;
        miner: string;
        uri: string;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  takeOffice: TypedContractMethod<
    [
      epochId: BigNumberish,
      deadline: BigNumberish,
      maxPrice: BigNumberish,
      uri: string
    ],
    [bigint],
    "payable"
  >;

<<<<<<< HEAD
  tier1Price: TypedContractMethod<[], [bigint], "view">;

  tier2Price: TypedContractMethod<[], [bigint], "view">;

  tier3Price: TypedContractMethod<[], [bigint], "view">;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  v2StartTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ABS_MAX_INIT_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EPOCH_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HALVING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_DPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INIT_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NEW_PRICE_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TAIL_DPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "TIER1_MAX_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER2_MAX_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePendingTokens"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimOfficeRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTokens"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "getMintPrice"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingOfficeRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSlot0"
  ): TypedContractMethod<[], [TavernKeeper.Slot0StructOutput], "view">;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "getTokensOfOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeOfficeV2"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "initializeRPG"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "keepToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastClaimTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastOfficeClaimTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintTavernKeeper"
  ): TypedContractMethod<
    [
      uri: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintingRate"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeMint"
  ): TypedContractMethod<
    [to: AddressLike, uri: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKeepTokenContract"
  ): TypedContractMethod<[_keepToken: AddressLike], [void], "nonpayable">;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "setSigner"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTierPrices"
  ): TypedContractMethod<
    [_t1: BigNumberish, _t2: BigNumberish, _t3: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
=======
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    nameOrSignature: "slot0"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, string, string] & {
        locked: bigint;
        epochId: bigint;
        initPrice: bigint;
        startTime: bigint;
        dps: bigint;
        miner: string;
        uri: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "takeOffice"
  ): TypedContractMethod<
    [
      epochId: BigNumberish,
      deadline: BigNumberish,
      maxPrice: BigNumberish,
      uri: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "tier1Price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tier2Price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tier3Price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "v2StartTime"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "KeepTokenUpdated"
  ): TypedContractEvent<
    KeepTokenUpdatedEvent.InputTuple,
    KeepTokenUpdatedEvent.OutputTuple,
    KeepTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "OfficeEarningsClaimed"
  ): TypedContractEvent<
    OfficeEarningsClaimedEvent.InputTuple,
    OfficeEarningsClaimedEvent.OutputTuple,
    OfficeEarningsClaimedEvent.OutputObject
  >;
  getEvent(
<<<<<<< HEAD
    key: "OfficeRewardsClaimed"
  ): TypedContractEvent<
    OfficeRewardsClaimedEvent.InputTuple,
    OfficeRewardsClaimedEvent.OutputTuple,
    OfficeRewardsClaimedEvent.OutputObject
  >;
  getEvent(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    key: "OfficeTaken"
  ): TypedContractEvent<
    OfficeTakenEvent.InputTuple,
    OfficeTakenEvent.OutputTuple,
    OfficeTakenEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PreviousKingPaid"
  ): TypedContractEvent<
    PreviousKingPaidEvent.InputTuple,
    PreviousKingPaidEvent.OutputTuple,
    PreviousKingPaidEvent.OutputObject
  >;
  getEvent(
<<<<<<< HEAD
    key: "SignerUpdated"
  ): TypedContractEvent<
    SignerUpdatedEvent.InputTuple,
    SignerUpdatedEvent.OutputTuple,
    SignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TavernKeeperMinted"
  ): TypedContractEvent<
    TavernKeeperMintedEvent.InputTuple,
    TavernKeeperMintedEvent.OutputTuple,
    TavernKeeperMintedEvent.OutputObject
  >;
  getEvent(
    key: "TavernKeeperMintedWithSignature"
  ): TypedContractEvent<
    TavernKeeperMintedWithSignatureEvent.InputTuple,
    TavernKeeperMintedWithSignatureEvent.OutputTuple,
    TavernKeeperMintedWithSignatureEvent.OutputObject
  >;
  getEvent(
    key: "TierPricesUpdated"
  ): TypedContractEvent<
    TierPricesUpdatedEvent.InputTuple,
    TierPricesUpdatedEvent.OutputTuple,
    TierPricesUpdatedEvent.OutputObject
  >;
  getEvent(
=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryFee"
  ): TypedContractEvent<
    TreasuryFeeEvent.InputTuple,
    TreasuryFeeEvent.OutputTuple,
    TreasuryFeeEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "KeepTokenUpdated(address,address)": TypedContractEvent<
      KeepTokenUpdatedEvent.InputTuple,
      KeepTokenUpdatedEvent.OutputTuple,
      KeepTokenUpdatedEvent.OutputObject
    >;
    KeepTokenUpdated: TypedContractEvent<
      KeepTokenUpdatedEvent.InputTuple,
      KeepTokenUpdatedEvent.OutputTuple,
      KeepTokenUpdatedEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "OfficeEarningsClaimed(address,uint256)": TypedContractEvent<
      OfficeEarningsClaimedEvent.InputTuple,
      OfficeEarningsClaimedEvent.OutputTuple,
      OfficeEarningsClaimedEvent.OutputObject
    >;
    OfficeEarningsClaimed: TypedContractEvent<
      OfficeEarningsClaimedEvent.InputTuple,
      OfficeEarningsClaimedEvent.OutputTuple,
      OfficeEarningsClaimedEvent.OutputObject
    >;

<<<<<<< HEAD
    "OfficeRewardsClaimed(address,uint256)": TypedContractEvent<
      OfficeRewardsClaimedEvent.InputTuple,
      OfficeRewardsClaimedEvent.OutputTuple,
      OfficeRewardsClaimedEvent.OutputObject
    >;
    OfficeRewardsClaimed: TypedContractEvent<
      OfficeRewardsClaimedEvent.InputTuple,
      OfficeRewardsClaimedEvent.OutputTuple,
      OfficeRewardsClaimedEvent.OutputObject
    >;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    "OfficeTaken(address,uint256,uint256,string)": TypedContractEvent<
      OfficeTakenEvent.InputTuple,
      OfficeTakenEvent.OutputTuple,
      OfficeTakenEvent.OutputObject
    >;
    OfficeTaken: TypedContractEvent<
      OfficeTakenEvent.InputTuple,
      OfficeTakenEvent.OutputTuple,
      OfficeTakenEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PreviousKingPaid(address,uint256)": TypedContractEvent<
      PreviousKingPaidEvent.InputTuple,
      PreviousKingPaidEvent.OutputTuple,
      PreviousKingPaidEvent.OutputObject
    >;
    PreviousKingPaid: TypedContractEvent<
      PreviousKingPaidEvent.InputTuple,
      PreviousKingPaidEvent.OutputTuple,
      PreviousKingPaidEvent.OutputObject
    >;

<<<<<<< HEAD
    "SignerUpdated(address)": TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
    SignerUpdated: TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;

    "TavernKeeperMinted(address,uint256,uint256)": TypedContractEvent<
      TavernKeeperMintedEvent.InputTuple,
      TavernKeeperMintedEvent.OutputTuple,
      TavernKeeperMintedEvent.OutputObject
    >;
    TavernKeeperMinted: TypedContractEvent<
      TavernKeeperMintedEvent.InputTuple,
      TavernKeeperMintedEvent.OutputTuple,
      TavernKeeperMintedEvent.OutputObject
    >;

    "TavernKeeperMintedWithSignature(address,uint256,uint256,uint256)": TypedContractEvent<
      TavernKeeperMintedWithSignatureEvent.InputTuple,
      TavernKeeperMintedWithSignatureEvent.OutputTuple,
      TavernKeeperMintedWithSignatureEvent.OutputObject
    >;
    TavernKeeperMintedWithSignature: TypedContractEvent<
      TavernKeeperMintedWithSignatureEvent.InputTuple,
      TavernKeeperMintedWithSignatureEvent.OutputTuple,
      TavernKeeperMintedWithSignatureEvent.OutputObject
    >;

    "TierPricesUpdated(uint256,uint256,uint256)": TypedContractEvent<
      TierPricesUpdatedEvent.InputTuple,
      TierPricesUpdatedEvent.OutputTuple,
      TierPricesUpdatedEvent.OutputObject
    >;
    TierPricesUpdated: TypedContractEvent<
      TierPricesUpdatedEvent.InputTuple,
      TierPricesUpdatedEvent.OutputTuple,
      TierPricesUpdatedEvent.OutputObject
    >;

=======
>>>>>>> d9c80166f06c3f6075f2ba2e63c2d068690df2ca
    "TokensClaimed(uint256,uint256)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TreasuryFee(address,uint256)": TypedContractEvent<
      TreasuryFeeEvent.InputTuple,
      TreasuryFeeEvent.OutputTuple,
      TreasuryFeeEvent.OutputObject
    >;
    TreasuryFee: TypedContractEvent<
      TreasuryFeeEvent.InputTuple,
      TreasuryFeeEvent.OutputTuple,
      TreasuryFeeEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
